### PR TITLE
Fix skip logic for integration tests

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Fixes build failure reported in #263 when dependencies for `av` component are not available.

## Summary

Since https://github.com/ignitionrobotics/ign-cmake/pull/165, we need to check both the `SKIP_av` and `INTERNAL_SKIP_av` before building integration tests that require the `av` component. Otherwise the integration tests fail to build, as reported in #263.

~~~
/build/source/test/integration/video_encoder.cc:21:10: fatal error: ignition/common/VideoEncoder.hh: No such file or directory
   21 | #include "ignition/common/VideoEncoder.hh"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
~~~

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [X] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-24-citadel-edifice-fortress/1241/1
