### PR TITLE
Fixed compile error with ffmpeg-5.0.

### LINKED ISSUE #579: Build error ignition-common3_3.17 with ffmpeg-5.0
Hi, 

I had faced build error for ignition-common3_3.17 in Yocto.

log is as following.

```
 [13/64] /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot-native/usr/bin/aarch64-oe4t-linux/aarch64-oe4t-linux-g++ --sysroot=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot -Dignition_common3_EXPORTS -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/core/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot/usr/include/uuid -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0=/usr/src/debug/ignition-common3/3.17.0-r0                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0=/usr/src/debug/ignition-common3/3.17.0-r0                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -O2 -g -DNDEBUG  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -UNDEBUG -fPIC -fvisibility=default -fPIC -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot/usr/include/uuid -std=c++17 -MD -MT src/CMakeFiles/ignition-common3.dir/PluginLoader.cc.o -MF src/CMakeFiles/ignition-common3.dir/PluginLoader.cc.o.d -o src/CMakeFiles/ignition-common3.dir/PluginLoader.cc.o -c /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/src/PluginLoader.cc
| [14/64] /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot-native/usr/bin/aarch64-oe4t-linux/aarch64-oe4t-linux-g++ --sysroot=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot -DIGN_COMMON_BUILD_HW_VIDEO -Dignition_common3_av_EXPORTS -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/av/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/av/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/core/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot/usr/include/uuid -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0=/usr/src/debug/ignition-common3/3.17.0-r0                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0=/usr/src/debug/ignition-common3/3.17.0-r0                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -O2 -g -DNDEBUG  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -UNDEBUG -fPIC -fvisibility=default -fPIC -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot/usr/include/uuid -std=c++17 -MD -MT av/src/CMakeFiles/ignition-common3-av.dir/AudioDecoder.cc.o -MF av/src/CMakeFiles/ignition-common3-av.dir/AudioDecoder.cc.o.d -o av/src/CMakeFiles/ignition-common3-av.dir/AudioDecoder.cc.o -c /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/av/src/AudioDecoder.cc
| FAILED: av/src/CMakeFiles/ignition-common3-av.dir/AudioDecoder.cc.o
| /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot-native/usr/bin/aarch64-oe4t-linux/aarch64-oe4t-linux-g++ --sysroot=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot -DIGN_COMMON_BUILD_HW_VIDEO -Dignition_common3_av_EXPORTS -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/av/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/av/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/build/core/include -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot/usr/include/uuid -march=armv8-a+crc -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0=/usr/src/debug/ignition-common3/3.17.0-r0                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0=/usr/src/debug/ignition-common3/3.17.0-r0                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -O2 -g -DNDEBUG  -Wall -Wextra -Wno-long-long -Wno-unused-value -Wfloat-equal -Wshadow -Winit-self -Wswitch-default -Wmissing-include-dirs -pedantic -UNDEBUG -fPIC -fvisibility=default -fPIC -I/home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/recipe-sysroot/usr/include/uuid -std=c++17 -MD -MT av/src/CMakeFiles/ignition-common3-av.dir/AudioDecoder.cc.o -MF av/src/CMakeFiles/ignition-common3-av.dir/AudioDecoder.cc.o.d -o av/src/CMakeFiles/ignition-common3-av.dir/AudioDecoder.cc.o -c /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/av/src/AudioDecoder.cc
| /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/av/src/AudioDecoder.cc: In member function 'bool ignition::common::AudioDecoder::Decode(uint8_t**, unsigned int*)':
| /home/bchoi/nvidia-yocto-bsp/bchoi-build/tmp/work/armv8a-oe4t-linux/ignition-common3/3.17.0-r0/git/av/src/AudioDecoder.cc:160:33: error: 'AVCodecContext' {aka 'struct AVCodecContext'} has no member named 'ch_layout'; did you mean 'channel_layout'?
|   160 |           this->data->codecCtx->ch_layout.nb_channels;
|       |                                 ^~~~~~~~~
|       |                                 channel_layout

```

I fixed this error with my patch and hope to be checked it available.
BR,
Mark

[0002-Fix-compatibility-with-FFmpeg5.0.patch](https://github.com/gazebosim/gz-common/files/14521019/0002-Fix-compatibility-with-FFmpeg5.0.patch)

### PR DESCRIPTION
**Pull request by bchoineubility**
# 🦟 Bug fix

Fixes #579 

## Summary
When I try to build with ffmpeg-5.0, it occurred compile error by comparing patch `[PATCH] Fix compatibility with FFmpeg 5.0 (#325)`

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by mjcarroll** [comment]
Since this was originally released to support Ubuntu 18.04 Bionic, I think that we need to continue to maintain support for older versions of libav, in this case you should be able to do it like

```
#if LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(59, 24, 100)
        int numChannels = this->dataPtr->codecCtx->ch_layout.nb_channels;
#else
        int numChannels = this->dataPtr->codecCtx->channels;
#endif
```
